### ISSUE TITLE
Compilation without assertions (-Sa)

### ISSUE THREAD

**Issue by serztle** [Kromster80/kam_remake#217]
If it is compiled without assertions, there is a minor bug in
https://github.com/Kromster80/kam_remake/blob/a443534/src/houses/KM_Houses.pas#L590
The result is that at least bowman's shoot at random positions all over the map.
The return value of the function call should be checked separately.

**Comment by lewinjh** [comment]
You're right, assertions should be side-effect free. Would you like to submit a pull request to fix that line? (and check other asserts if you have time).

On a sidenote we have actually been leaving assertions enabled in release builds because they help to catch bugs (allows the player to send as a bug report with MadExcept). Generally if one of our assertions fails something has gone very badly wrong due to a bug and something else will fail soon anyway.

**Comment by lewinjh** [comment]
Fixed in #221
