### ISSUE TITLE
Bugfix for woodcutter cutting point

### ISSUE THREAD

**Issue by reyandme** [Kromster80/kam_remake#218]
There are couple known bugs now for new woddcutter cutting point:

1. This bug is better to show. Here it is: ![looks](https://puu.sh/tCqoP/a6141daf10.png)
so woodcutter go all the way around unwalkable tiles, doesn't matter how far is it.

2. Building a house over cutting point will stop woodcutter working, because initially algorithm try to build walk route from woodcutter house to his cutting point, then choose place where he can cut/plant tree. There is no such a route, then this bug occurs.
Here how it looks: ![looks](https://puu.sh/sFjmk/d4462bb1a1.png)
Not sure if it's ok to draw cutting point mark over the house. 

Possible solutions:
1) We can restrict woodcutter walking distance, or flag placement. Both options are not good enought:
a. if woodcutter can't walk too far, but the marker is where it was, it will be very confusing for player - so he will need somehow approximately evaluate, when woodcutter go, and where he can't
b. if we restrict marker placement, so f.e. in the situation on screenshot we will calc walkable route when marker is placed and then put onto the most far tile. Its ok. But then what to do if after some terrain changes or building new houses, then walkable route distance to cut. point could increase. Reevaluate walking distance on these event ? Probably not good solution too.

2) 
a. We can find closest walkable tile to current cut. point and let woodcutter use it as his cutting point. 
But then you can have cut. point over the house, while you can't get it if you try to place it over existing house (kind of a trick to get such point).
b. Inform player about this occasion after plan was placed, then player will need to replace cut. point manually again. And no problem with 'tricks' here (which I described in preceding paragraph).

P.S. btw similar bug is for Barracks rally point - if you build house over it soldiers will stop gathering near rally point.

@Kromster80 @lewinjh what do you think ?

**Comment by lewinjh** [comment]
1. Maybe it's ok to ignore this? Yes, it's possible to make your woodcutter walk further than he normally would, but it doesn't give you an advantage since he wastes a lot of time walking and it's still within a small radius around the house. It should also be fairly obvious to the player if they place the cut point on the far side of a mountain, so I don't think this situation can occur by accident.

2. Regarding the cut/rally point being over a house/unwalkable tile, maybe when a soldier/woodcutter attempts to use the rally point it should call a new function Barracks.ValidateRallyPoint(). This would check if the rally point can't be walked to, and if so move it towards the barracks one tile at a time until it either finds a tile which can be walked to (and sets the rally point there) or reaches the barracks door and sets the rally point to the initial "not set" state.

**Comment by reyandme** [comment]
1. For woodcutting and planting this is a no preferences, as you said, but then woodcutter can be used to discover unrevealed areas behind some mountain. That is what I want to prohibit. We have discovering laborer already and its better to not make a new one option for this 'hacks'

2. I like your idea, that we can replace rally point in this situation and do not show it over house. I think this solution is good enough.

But bullet 1 is still unclear for me

**Comment by lewinjh** [comment]
I don't think that matters, if the player wants to reveal behind the mountain they can use a builder anyway. So the woodcutter doesn't give you anything new, and it's worse because you have to build next to the mountain and waste the time of your woodcutter.

Unless the cut point is in an unexplored area which you can't do with builders. Maybe make it so you can't place the cut point in unexplored areas? (although house visibility range probably reveals the valid cut point range already?)

**Comment by reyandme** [comment]
Even if the area is visible woodcutter will reveal map on the way to it. But ok, then we could use labourer.
What about unexplored area - yes, house visibility range is more then cutting point max disctance.
So we can ignore this issue, ok.

**Comment by reyandme** [comment]
fixed in #230
