### ISSUE TITLE
Ability to mark maps as a favourite (gold star)

### ISSUE THREAD

**Issue by reyandme** [Kromster80/kam_remake#220]
From Buglist.txt:
Ability to mark maps as a favourite (gold star) so they appear at the top of the list (find your favourite maps without scrolling through whole list)

- - - - - - - - - - - - - - - - - - - -

Possible UI:
We can add new column with star in it for list in Lobby and Map Editor. For favorite map here is a star, for not favourite - star outline ('empty star'). Pics are clickable, so player can set/unset favourite status. 

We can even add kind of a rating here - 5 stars max, 0 min, then player could sort maps by number of stars. By default all maps are sorted by name and rating (first by name, then apply rating sort, then because of stable sort algorithm MergeSort, that we use now, same rated maps will be sort properly)

May be we can add same stars in MapEd menu where player also can set/unset them (it will need some place in MapEd menu to show these stars, but we can change controls placement on MapEd menu page, so minimap can be in the top left corner then map list will get enought width)

Implementation:
'Favorite' maps stored locally in ini file (by Name or CRC or both?) with their rating (probably we can add some format to add name/CRC/Rating value in 1 line, similar as I did for Ware Distribution). Then on maps scan new 'Favourite' property will be set for favorite maps. 

We already have gold star for Host, we can reuse it here. Then only new 'empty star' icon is needed.

**Comment by thunder6** [comment]
Good afternoon,

I  have very similar problem with replay folder which need much more time to load the list. Sometimes need to wait approximately around a minute to be able to jump until the end. I dont have more files than 2697(divide it with 3= replays) in the replay folder(a bit more than 2GB). I use to save many games still what I spectated also.
It would be nice if this list could preload itself somehow in the backgroud when the game started up.

Idea2: Sometimes players want to share more than 2 or 3 replays with other players in the same time. In this case the only one downloaded file is not the best solution because the second downloaded file will overwrite the first one. could you restucturize the replay handling? I mean it could work as like the downloaded maps which have a second folder MapsMP and MapsDL so the replays would have also SaveMP and SaveDL or something like this.
MAny thanks!

Anyway the maplist is working nicely. ;)

Have a nice day!
t

**Comment by reyandme** [comment]
Hi, thunder!

Interesting ideas, I think they worth implementing, but its better to discuss them in separate thread. Can you create 2 separate Issues for them ?

Thanks!

**Comment by lewinjh** [comment]
I don't think a rating is necessary. Just "favourite" or "not favourite" should be fine. It's intended so you can find the maps that you play most often without scrolling through the entire list. Maps should be sorted by favourite status after normal sorting, so favourites are always at the top and within the favourites/non-favourites the selected sorting is applied.

Storing in INI sounds good.

Icon should be easy to make, probably just a greyscale version of the current one.

Regarding @thunder6's comment: Wow. We never designed it to cope with so many replays. There are probably some optimisations to be made here. Rather than rescanning every time you open that menu we could scan maps/saves once on startup then use file system watching to be notified when files are added/delete/renamed and rescan only those modified files. As rey said this should be a separate issue.

**Comment by reyandme** [comment]
Do we need to be able to set/unset favourite status only in lobby or in MapEd also ?

**Comment by lewinjh** [comment]
Only in lobby is ok IMO. No need to show stars in MapEd, this is only intended for making it faster to select one of your favourite maps in the lobby.

**Comment by Kromster80** [comment]
I'd suggest to add a new column for rating and allow to sort by it. Combined with previous improvements made by switching to stable sort, sorting by name and then by stars would produce "with stars A-Z, without stars A-Z" list.

To use rating or stars? I don't have a strong opinion. This could clutter UI, but also could be helpful to some players. Let's add stars first, then look into rating scores.

**Comment by reyandme** [comment]
OK

**Comment by lewinjh** [comment]
@Kromster80 I don't think a 1-5 rating makes sense if this is just a private/local feature. A 1-5 rating would make sense if the maps are in an online database.

Allowing sorting by favourite like any other column sounds ok, as long as the default sort is "sort by name, then sort by favourite, so favourites are at the top (and favourites/non-favourites are each alphabetically sorted)". This means it's fast to choose one of your favourites without changing sorting options.

**Comment by reyandme** [comment]
1-5 is too much, I agree, but 1-3 may become usufull when player want to separate all his maps into different level of 'favourite'. 
There are plenty of unnoficial KaM maps, and some ppl like to have all of them

**Comment by thunder6** [comment]
well my maplist is long, very long. I could sort more than 40 as favourite maps. What if only 3 or 5 maps would be selectable/choosable to the top or into the first region of the maplist before 'A'. There are some advertisement pages where if you pay then your advertisement will jump always to top or to the first line. 

Personaly I think the maplist is working well. Maybe a 'choose random map' button would be cool. Many times the player can not agree what map be played:D It would be fun to give a random result from a prefilled list.

Rating maps would be nice only if there would be collected votes. 
Or using the popularity list which is turned off after some abusing cases? :S

Anyway I made a huge table which relative measuring the mapquality on a 0-10valued scale.
If a map value is over 7 than that map could be well playable with 60min PT. from 10 only 1point is subjective all other 9 points are measurable. 
http://screenshot.sh/mGwa0FIw3sgJK

**Comment by reyandme** [comment]
> I could sort more than 40 as favourite maps. What if only 3 or 5 maps would be selectable/choosable to the top or into the first region of the maplist before 'A'. 

I do not understand clearly what you mean. What is wrong if you will have 40 favourites maps on the top of the list after sorting? 
Currently I believe you cant find any map by scrolling - probably you use keyboard search mostly. So after this improvement you will see 40 best maps at the top of the list, and you will be able to scroll through these 40 maps to get map which you want. All other maps will be still easy to find with keyboard search (when you start typing map name).

Other players, with less maps (most of the players) will have even easier choices (lets say they will have 10 favourite maps).

Am I missing something ?

Random map - may be :) But then we will need to add filters for maps. 
F.e. in same dropdown menu where we choose map, on one side of it add filter Panel. It can contain  checkbox for 'Favourite' maps, 2 dropdown lists (for # of players and map size) and button 'Random map' which randomly select map from list (for current filters). But ofc its minor improvement, 'just for fun'.

**Comment by reyandme** [comment]
implemented in #232
