### ISSUE TITLE
Fixin some market values?

### ISSUE THREAD

**Issue by thunder6** [Kromster80/kam_remake#266]
Hello!
About some market values.
Personaly i think there are some not useable trades and some which has no sense because has as high price. For example stone to horse 32:S
I think to should recalculate values which are over 10. 
For example if the price is 1:16 the that could be reduce to 1:13.
So the new price would be 10+(16-10)/2. In this case the stone to horse trade would be better also 1:32 to 1:21.
I know the market is very sensitive but there are wares which has no sense to trade, wares which have very high price, ware wich more expensive because the fractions, the market has tax and the market is not counting with the transportation time and with the numbers of serfs either. So 32 stone trading is much more than talking about only the trades. Need 32 serfs which won't work in this tim in the city. 
 Personaly i traded timber to horse and was total useless:D 1:11.

so maybe some discount for the higher price wares? or using a function which reducing the price if that is ver high? 
I think to red values are very expensive.
Bests!
t

![market recalculate some values](https://cloud.githubusercontent.com/assets/11676710/23082646/891ee026-f55a-11e6-901c-504c874656b0.jpg)

**Comment by Kromster80** [comment]
Thanks for the detailed table!

Market prices are calculated based on resource production times and a few constants.

I guess we *do* want to discourage trading of early raw wares for late-game wares and weapons. Otherwise players would be incentivised to skip majority of the ware production chains in favor of mass raw materials mining and trading for warfare.

*This is also one of the reasons we don't want to have Town Hall in the game - it undermines the game's core gameplay.*
