### ISSUE TITLE
Any plan to release a Linux version?

### ISSUE THREAD

**Issue by ghevge** [Kromster80/kam_remake#439]
Any plan to release a Linux version?

**Comment by LauraRozier** [comment]
There have been attempts, but due to required safety measures this is not yet possible.
Due to differences in Windows and Linux the clients will not result in the same hash values, meaning for now only Linux can play with Linux and Windows only with Windows.

Perhaps the master server could be changed to determine which versions are valid/can play with each other. It will require some more work and a proper action plan. :)

As a heads-up, we did play around with Linux compilation. Just need to wait for Rey's repo to calm down before we can have some decent time to fix incompatibilities.
