### ISSUE TITLE
How can I fix some bugs in Chinese translations?

### ISSUE THREAD

**Issue by XenoAmess** [Kromster80/kam_remake#449]
as title.
And I will also try to add Chinese translations in some missions.

**Comment by XenoAmess** [comment]
But I want to know before I take actions, that if the project is still well maintained or not? Because I see no more recent build releases anymore on your website after 2015.
I don't want to waste time anyway.

**Comment by reyandme** [comment]
Hi!
This repository is not much active indeed, since main dev @Kromster80 is working on other new game Knights Province.
But I am working on next release version for KaM Remake in my own repository. I have plans to make new release version, but its not clear when yet.

So afterall your help in translation will not vain. 
Btw I will need help in translation for new texts for next release as well. Hope you can help in that too

**Comment by Kromster80** [comment]
@XenoAmess Thanks for asking! (also got your email). @reyandme is right. this KaM Remake repo is no longer in active development. @reyandme fork (https://github.com/reyandme/kam_remake) is the active one now.
