### ISSUE TITLE
Serfs should start delivering stone/timber to Builders as soon as they start the work on road/wine plans

### ISSUE THREAD

**Issue by TehPlayer14** [Kromster80/kam_remake#9]
Serfs should go for the stone/wood when Builders start digging (like in TPR)

**Comment by Kromster80** [comment]
Did this really work like so in TPR ? I had an impression that in TSK and TPR serfs acted the same, going to deliver the stone/wood only after the worker would started working on the plan and paused in need for the stone/wood.

All in all though, this would be a good improvement.

**Comment by TehPlayer14** [comment]
Here you go its old video but still it explains it was there https://youtu.be/x2ayjxaioEE

The diffrence was in vid about ~2s

**Comment by Kromster80** [comment]
Thanks for the reference! :-)

**Comment by avdept** [comment]
I always thought that mats were delivered only when worker stopped preparing for building. This makes sense if for ex. your worked died or was killed in action, and therefore serf wastes lots of time to return(if no killed)

**Comment by Kromster80** [comment]
99.9% of the time worker would not die, so we can slice off these 5-8 seconds of each road, that can add to a very significant number indeed :-)

**Comment by avdept** [comment]
It's your decision, but imagine real life. Are bricks being delivered when workers building safe wall?

—

**Comment by Kromster80** [comment]
What do you mean?

**Comment by Kromster80** [comment]
Implemented. Will be in next release.

**Comment by TehPlayer14** [comment]
Whoa Nice Thanks Krom

**Comment by TehPlayer14** [comment]
Will be there soon a new version including it ? because it can change gameplay quite a lot

It will speed up building in general.

**Comment by Tassl3hoff** [comment]
This won't nerf the computer AI will it.

**Comment by Kromster80** [comment]
@Michal1324: Maybe next year.
@Tassl3hoff: I can not understand what you mean by that.

**Comment by LauraRozier** [comment]
@Kromster80 , about what @Tassl3hoff wrote, I think what the worries are that it might give the enemy AI a disadvantage over the players, by building the roads slower.
Yet, due to the huge amount of reading the code I did for the fix of the ArmorSmithy, I read through the full serf action handling and by accident also that of the worker, I am sure it will not.
The AI uses the same classes for serfs and workers, for as far as I know.
It should be the same even with the enhancement. :)
You build roads a bit faster but the AI will too.
